sudo: required
language: rust
rust:
- stable
- nightly
addons:
  apt:
    packages:
      -  libsdl2-dev 
matrix:
  fast_finish: true
  allow_failures:
    - env: RUSTKCOV
    - env: RUSTCOV
  include:
  - env: RUSTFMT
    rust: stable
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --check
  - env: RUSTCOV
    rust: nightly
    install:
    - cargo tarpaulin --version || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    script:
    - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    - cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash)
  - env: CLIPPY
    rust: stable
    install:
      - rustup component add clippy-preview
      - cargo clippy --all-features

os:
- linux

install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install windows-sdk-10.0; fi # windows workaround (for now)

script:
- cargo check --verbose --features render_tcod
- cargo check --verbose --features render_doryen
- cargo test --verbose

cache:
  cargo: true