sudo: false
language: rust
rust:
- 1.30.0  # Oldest supported
- stable
# - beta
# - nightly
matrix:
  include:
  - env: RUSTFMT
    rust: 1.30.0  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --check
  - env: RUSTCOV
    rust: 1.30.0
    install:
    - cargo install cargo-kcov
    script:
    - cargo kcov
os:
- linux
# - osx
# - windows

install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install windows-sdk-10.0; fi # windows workaround (for now)

script:
- cargo check --verbose
- cargo test --verbose

cache:
  cargo: true