sudo: required
language: rust
rust:
- stable
# - beta
- nightly
matrix:
  allow_failures:
    - env: RUSTKCOV
  include:
  - env: RUSTFMT
    rust: stable
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --check
  - env: RUSTKCOV
    rust: stable
    install:
    - cargo kcov --version || cargo install cargo-kcov
    - cargo kcov --print-install-kcov-sh | sh
    script:
    - cargo kcov
  - env: RUSTCOV
    rust: nightly
    install:
    - cargo tarpaulin -version || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    script:
    - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  - env: CLIPPY
    rust: nightly
    install:
      - rustup component add clippy-preview
      - cargo clippy --all-features

os:
- linux
# - osx
# - windows

install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install windows-sdk-10.0; fi # windows workaround (for now)

script:
- cargo check --verbose
- cargo test --verbose

cache:
  cargo: true