language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy --all-targets --all-features
  - cargo test
  - cargo build
