language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
    - rust: nightly
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
cache: cargo
before_script:
  - rustup component add clippy-preview
script:
  - cargo clean
  - cargo clippy --all-features
  - cargo test
  - cargo build
  - "if [[ \"$TRAVIS_RUST_VERSION\" == nightly ]]; then \
    cargo bench \
  fi"

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi