language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
    - rust: nightly
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
cache: cargo
before_script:
  - rustup component add clippy-preview
  - cargo clean
jobs:
  include:
    - stage: "clippy"
      script: cargo clippy --all-features
    - stage: "test"
      script: cargo test
    - stage: bench
      rust: nightly
      script: cargo bench
    - stage: coverage
      rust: nightly
      script: cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
