language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
    - rust: nightly
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force
  fi
cache: cargo
before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy --all-features
  - cargo test
  - cargo build

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo bench
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi