language: rust
rust:
 - stable
 - beta
 - nightly
 addons:
  apt:
    packages:
      - kcov
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before_script:
  - rustup component add clippy-preview
  - cargo install cargo-kcov
script:
  - cargo clippy --all-features
  - cargo test
  - ./ci/bench.sh
