sudo: required
language: rust
rust:
- 1.30.0  # Oldest supported
- stable
# - beta
- nightly
matrix:
  include:
  - env: RUSTFMT
    rust: 1.30.0  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --check
  - env: RUSTCOV
    rust: 1.30.0
    install:
    - cargo kcov --version || cargo install cargo-kcov
    - cargo kcov --print-install-kcov-sh | sh
    script:
    - cargo kcov
  - env: RUSTCOV
    rust: nightly
    install:
    - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    script:
    - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
os:
- linux
# - osx
# - windows

install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install windows-sdk-10.0; fi # windows workaround (for now)

script:
- cargo check --verbose
- cargo test --verbose

cache:
  cargo: true